name: CI

on: push

# Look if we want to split integration tests into it's own job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/gundalow_collections/grafana
      - name: Install Ansible 2.9.0rc1
        run: pip install ansible==2.9.1 --disable-pip-version-check
      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
#     - name: Run unit tests
#       run: ansible-test units --docker -v --color
#     - name: Run integration tests on Python 2.7
#       run: ansible-test integration --docker -v --color --retry-on-error --python 2.7
      - name: Run integration tests on Python 3.6
        run: ansible-test integration --docker ubuntu1804 -v --color --retry-on-error --python 3.6
